version: 3.4
services:
  web:
    build: .
    command: scripts/start.sh
    volumes:
      - .:/app
      - yarn:/app/node_modules
    ports:
      - 80:3000
    depends_on:
      - db
    env_file:
      - .env.docker
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=o_jogo_do_bicho
volumes:
  yarn:
